### PR TITLE
Merge with upstream version 2017-07-13 08:48

### PR DESCRIPTION
**Pull request by meyerj**
Changelog since the last merge (#3):
```
2017-07-13 08:48  sanchouss_
      * bug 146; 
      * bug 147 - Being prepared for Removing Deprecated Exception Specifications from C++17

2016-11-11 18:48  sanchouss_
      * Numerous fixes;
      * Added .target property for the ConsoleAppender to allow printing to STDERR 
      * Added method Category::shutdownForced(). It releases more memory than shutdown() by deleting all appenders. 
      Category::shutdownForced() may be invoked several times, not only at the end of program.
```

See full [Changelog](https://github.com/orocos-toolchain/log4cpp/blob/2e117d81e94ec4f9c5af42fcf76a0583a036e106/ChangeLog).

### CODE REVIEW

**Comment by meyerj** [comment]
We have to review the changes in the Appender class and eventually revert it.

**Comment by francisco-miguel-almeida** [comment]
> We have to review the changes in the Appender class and eventually revert it.

Could this be related to https://github.com/orocos-toolchain/log4cpp/issues/13?

**Comment by meyerj** [comment]
> Could this be related to #13?

No. This low priority patch is not merged into `toolchain-2.9` or `master` yet.

**Comment by medenes** [comment]
Hi. Is here any blocking issue that not allow to merge this PR into master? bug 147 is the most wanted for me.

**Comment by snrkiwi** [comment]
WFM. We should try to keep up ... probably need to do another sync at some point soon also ...

**Comment by meyerj** [comment]
> We have to review the changes in the Appender class and eventually revert it.

I personally did not run any tests so far to check whether the update breaks real-time logging in [OCL Logging](https://github.com/orocos-toolchain/ocl/tree/toolchain-2.10/logging). From looking at the diff I do not see a problem, but also did not go over all patches in detail.

If someone could confirm that the patch does not break OCL, we can merge and consider it for a [toolchain-2.10](https://github.com/orocos-toolchain/log4cpp/tree/toolchain-2.10) release.

> WFM. We should try to keep up ... probably need to do another sync at some point soon also ...

The branch merged here is still the latest from the upstream repo at https://sourceforge.net/p/log4cpp/codegit/ci/master/tree/.

**Comment by snrkiwi** [comment]
I think that the Appender related changes are ok, though why they needed the complexity related to the Appenders Map is not evident. Shrug ... I don't see any changes that might effect real-time

**Comment by meyerj** [comment]
Also merged into `toolchain-2.10` in https://github.com/orocos-toolchain/log4cpp/commit/4c6df4acf88f4f003a1de9a7dba32cf460acf125.

**Pull request merged**
